### ISSUE TITLE
move to ropensci-org?

### ISSUE THREAD

**Issue by maelle** [ropenscilabs/ropensci_citations#4]

**Comment by sckott** [comment]
sure. you'd have to update urls you use for citations in roweb3 i assume?

**Comment by maelle** [comment]
Yes

**Comment by maelle** [comment]
URL updated, and the citations page looks great (well it'll look better with images if we add them) https://roweb3-hugo.netlify.app/citations/

**Comment by sckott** [comment]
nice work, looks great

**Comment by maelle** [comment]
well awesome work collecting all these citations :clap:
